var car = "subaru";
console.log("Is car == 'subaru' , I predict TRUE.");
console.log(car == 'subaru');
console.log("\n Is car == 'Subaru' , I predict FALSE.");
console.log(car == 'Subaru');
console.log("\n Is car === 'subaru' , I predict TRUE.");
console.log(car === 'subaru');
console.log("\n Is car == 'honda' , I predict FALSE.");
console.log(car == 'honda');
console.log("\n Is car != 'honda' , I predict TRUE.");
console.log(car != 'honda');
console.log("\n Is car != 'subaru' , I predict FALSE.");
console.log(car != 'subaru');
console.log("\n Is car != 'BMW' , I predict TRUE.");
console.log(car != 'BMW');
console.log("\n Is car == 'BMW' , I predict FALSE.");
console.log(car == 'BMW');
console.log("\n Is car != 'Honda' , I predict TRUE.");
console.log(car != 'honda');
console.log("\n Is car == 'Honda' , I predict FALSE.");
console.log(car == 'honda');
